language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.2

gemfile:
  - gemfiles/clean.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile

script: 'bundle exec rspec'

notifications:
  email: false

addons:
  code_climate:
    repo_token: def01fea93ef7e5af7b536817182cb7951f9aac0e151bf544584901a689ea8f3
